server:
  port: 8080
# Database properties
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    platform: postgres
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234root}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_SERVER_PORT:5432}/${DB_NAME:test_data}?createDatabaseIfNotExist=true
    initialization-mode: always
  jpa:
    database: POSTGRESQL
    show-sql: true
    # set generate-ddl as false before pushing to production
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        default_schema: public
        # Set the ddl-auto to none before pushing to production.
        #ddl-auto: none
        ddl-auto: create-drop
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
# API Documentation settings
com.sampleapp.configuration:
  security:
    endpoints:
      unsecured:
        - "/v3/api-docs/**"
        - "/swagger-ui.html"
        - "/swagger-ui/**"
    api:
      documentation:
        title: Sample-App
        description: Sample App with auth login
    auth:
      token:
        secret: isymphony
        expiration-interval-in-hours: 168